version: '3'
services:
  api:
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env/.env_api
    depends_on:
      - database

  database:
    image: 'postgres:16'
    ports:
      - 5432:5432
    env_file:
      - .env/.env_db