spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/default_database}
    username: ${DB_USER:username}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update